---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/sre-agent-app.yaml

patches:
  - target:
      kind: Application
      name: sre-agent
    path: service_account_patch.yaml
