---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kyverno/kyverno-app.yaml
  - monitoring/monitoring-app.yaml
  - sre-agent/sre-agent-app.yaml
  - vault/vault-app.yaml
